version: '3'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend  # Apunta al submódulo del frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev